title: Suvedha Data Science Projects
description: Here is a list of data science projects that I have worked on.
theme: just-the-docs

url: https://suvedharam97.github.io

aux_links:
  GitHub Repository: https://github.com/suvedharam97
